spring.application.name=Learn-SpringAI

# Gemini
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/myTestVectorDb
spring.datasource.username=my-user
spring.datasource.password=password

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.table-name=vector_store