spring.application.name=Learn-SpringAI
# Ollama Server
spring.ai.ollama.base-url=http://localhost:11434

# Chat Model
spring.ai.ollama.chat.options.model=qwen2.5:7b
spring.ai.ollama.chat.options.temperature=0.7

# Embedding Model (if you're using RAG)
spring.ai.ollama.embedding.options.model=nomic-embed-text
spring.datasource.url=jdbc:postgresql://localhost:5434/myTestVectorDb

spring.datasource.username=my-user
spring.datasource.password=password
spring.ai.vectorstore.pgvector.initialize-schema=true

spring.ai.vectorstore.pgvector.dimensions=768

spring.ai.vectorstore.pgvector.table-name=vector_store